language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "8"

script:
  - npm install
  - npm run lint

language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - matthew.brown.js@gmail.com
    on_success: always
    on_failure: always
node_js:
  - '9'
git:
  depth: 3
script:
  - gatsby build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: develop
